services:
  scheduling:
    image: cpugpu:1.0.0
    environment:
      - EPSILON=0.1
      - INSTANCE_MINJOBS=10
      - INSTANCE_MAXJOBS=50
      - INSTANCE_MINMACHINES=5
      - INSTANCE_MAXMACHINES=30
      - ES_HOST=192.168.178.101
      - ES_INDEX=cpugpu-0.1
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy
    restart: always